FROM centos:latest
# DockerFile Centos Steamcmd

RUN yum -y install glibc.i686 libstdc++.i686 && yum clean all && rm -rf /var/cache/yum &&\
    mkdir /Steam && cd /Steam &&\
    echo "#!/usr/bin/env bash \
if [ ! -f /Steam/steamcmd.sh ]; then \
    curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - && ./steamcmd.sh +exit && echo 'Finished install' \
fi\
    " >> /Steam/firstTimeInstall.sh &&\
    chmod +x firstTimeInstall.sh
ENTRYPOINT /Steam/firstTimeInstall.sh    
# VOLUME /DedServers # Not needed better practice is use Named Volumes.
# From here you can go into the container shell and start downloading and configure the servers.
